Add `SCRIPTISTO_CACHE_DIR` environment variable + showcase in new Dart template, support hashing additional paths such as multiple source files or directories
igor-petruk/scriptisto pull request #30
Opened 2020-11-01 21:05 UTC by AndiDog

Sorry, didn't open an issue before. Please add one if this feature isn't clear. To me, hashing more than just the script file itself is essential since many programs consist of multiple source files. This change allows listing files and directories which will trigger a rebuild if their modification time changed (same as scriptisto already does on the source script file). A new Dart template was added and used as show case for an – also new – `SCRIPTISTO_CACHE_DIR` environment variable, which helps the script access any further built artifacts.

- [ ] Tests pass – Manually tested, didn't find any automated tests.
- [ ] Appropriate changes to README are included in PR – No. Changes should be described in the Wiki once merged.

2022-12-09 22:38 UTC, igor-petruk commented
Hi, due to personal circumstances I did not look into this project for a while, but now I am back and happy to take a look. Sorry that I ignored this for so long, please let me know if you no longer have time for this.

2022-12-09 22:49 UTC, igor-petruk requested changes
At high-level, is the goal of this PR to add Dart support, and all these features are required to make it happen? Or the features themselves are useful?

In other words, if I was able to produce a dart template without any of this, would it suffice?

I've left some high level comments too, we can discuss them before I go over the main body of the change in `build.rs`.

2022-12-09 22:49 UTC, igor-petruk commented on data/templates/dart.dart
> +# 1) mkdir -p cli && echo "void main(List<String> arguments) { print('Hello Dart, arguments=' + arguments.toString()); }" >cli/main.dart
I see what you are doing with this, but can you please clarify why is it better than using "files". Every file there is embedded in the script, so naturally every change counts. 

I would expect a dart template to looks inverse to this: there is a "file" for the shell script. The main body of the script is the dart file. 

Are you trying to introduce the development flow, where scriptisto script is just a "make-and-run.sh", but your actual code is elsewhere?

2022-12-09 22:49 UTC, igor-petruk commented on data/templates/dart.dart
> +# build_cmd: cache_dir="$(pwd)" && cd "$(dirname "${SCRIPTISTO_SOURCE}")" && dart2native "cli/main.dart" -o "${cache_dir}/my-dart-program"
```suggestion
# build_cmd: cache_dir="$(pwd)" && cd "$(dirname "${SCRIPTISTO_SOURCE}")" && dart compile exe "cli/main.dart" -o "${cache_dir}/my-dart-program"
```

2022-12-09 22:57 UTC, igor-petruk requested changes
The reason I asked, is that I've just tried and this works without any problems.

https://github.com/igor-petruk/scriptisto/blob/dart/data/templates/dart.dart

If all you want is Dart, I can just add that to master and release.

2023-01-08 14:19 UTC, igor-petruk commented
I've merged the offered dart template, so it may conflict now

2023-01-12 17:42 UTC, AndiDog commented
Yes indeed, the existing Dart template that you added in December works. But often times, a program doesn't just have a single file (with a `main` function, for example), but more dependencies. And scriptisto should rebuild in that case. What about we add such a more complex template, separate from the simple template? I can adjust the PR accordingly if you agree.

2023-01-19 22:19 UTC, igor-petruk commented
Ok, I think I now understand what this feature does. I was assuming before that it hashes files in the target directory, not in the script directory. In that case it was not clear how is it different from just using `files`.

I am happy to accept the change with a few changes:

* As discussed, let's rename the template, e.g. `dart_multifile` or feel free to suggest a better name.
* I would not include large instructions into the script body itself. You can just assume `cli/main.dart` is already there and later on I can write a Wiki section and include a reference to it. It's just comments from the documentation and comments from the scriptisto settings merge into a single wall and it makes the feature demonstration harder.
* Let's rename `hash_additional_paths` from what it does to what it is. Instead of having an implementation detail in the name (the fact that it will hash something), we could just name it `extra_src` or `extra_src_paths` or something similar.
* *Optional if you are interested, or I can do it later*
  *  `cache_dir="$(pwd)" && cd "$(dirname "${SCRIPTISTO_SOURCE}")"` just looks like an extra feature where we simply could say `build_in_script_dir: true` and make the `SCRIPTISTO_CACHE_DIR` available to `build_cmd` instead of the `cache_dir`. Does it look like a good feature? 

Thank you for your pull request!

2023-03-10 12:06 UTC, AndiDog commented
Applied all your suggestions and rebased onto latest `master` 😀

2023-04-10 10:21 UTC, merged

2023-04-10 10:24 UTC, igor-petruk commented
Released 2.1.0